### ISSUE TITLE
Better documentation regarding MMU

### ISSUE THREAD

**Issue by atirutw** [SolraBizna/j6502#2]
The documentation for MMU is specially dry and I'm trying to figure out how it works. The only thing I figured out is that there's bank switching and writing to areas more than installed RAM can access results in a "black hole" behavior.

EDIT: Still just guesswork, but maybe swicthing bank switches out a choosen page of memory?

**Comment by SolraBizna** [comment]
Hm, it seems I neglected to actually expand precisely on what the `$200`-`$23F` registers do and how the memory is mapped. Scanning the documentation again, I'm surprised I managed to implement and document so much when I was on such a time crunch.

Improving this documentation seems like a fun task to do while I'm sick (not sarcasm). I should have slightly improved documentation committed soon.

**Comment by atirutw** [comment]
> while I'm sick

I hope you get well soon :+1: . I also have some plans to fork and improve the docs.

**Comment by SolraBizna** [comment]
I added a lot of stuff about memory mapping, and also clarified a few other parts of the documentation. Hopefully this helps.
